name: CLI
about: Suggest an idea for the Ionic CLI
title: ''
labels: 'ionitron: cli'
body:
  - type: markdown
    value: "Please do not submit bug reports or feature requests related to the Ionic CLI. Instead, please submit an issue to the [Ionic CLI Repository](https://github.com/ionic-team/ionic-cli/issues/new/choose)."
