name: Documentation
description: Suggest an improvement for the Ionic Framework documentation
labels: 'ionitron: docs'
body:
  - type: markdown
    attributes:
      value: "Please do not submit issues on how to improve or fix the documentation. Instead, please submit an issue to the [Ionic Docs Repository](https://github.com/ionic-team/ionic-docs/issues/new/choose)."
